// Code generated by goctl. DO NOT EDIT.
package types

const (
	// Success | 成功
	Success = 10000
	// Fail | 失败
	Fail = 10001
	// NotFound | 未找到
	NotFound = 10002
)

// The basic response with data | 基础带数据信息
// swagger:model BaseDataInfo
type BaseDataInfo struct {
	// Error code | 错误代码
	Code int `json:"code"`
	// Message | 提示信息
	Msg string `json:"msg"`
	// Data | 数据
	Data any `json:"data,omitempty"`
}

type UploadInfo struct {
	// Name | 文件名
	Name string `json:"name"`
	// url | 文件url
	Url string `json:"url"`
}